# Generated by Django 4.1.5 on 2023-11-22 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Affliction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affliction', models.CharField(default='None', max_length=200, verbose_name='고민')),
                ('affliction_detail', models.CharField(default='None', max_length=200, verbose_name='고민상세')),
            ],
            options={
                'verbose_name': '사용자 고민',
                'verbose_name_plural': '사용자 고민',
                'db_table': 'USERAFFLICTION_TB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User_Incongruity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incongruity', models.CharField(default='None', max_length=100, verbose_name='부적합')),
            ],
            options={
                'verbose_name': '부적합',
                'verbose_name_plural': '부적합',
                'db_table': 'USERINCONGRUITY_TB',
            },
        ),
        migrations.CreateModel(
            name='User_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_nickname', models.CharField(max_length=10, null=True, verbose_name='카드 닉네임')),
                ('user_birthday', models.CharField(max_length=10, null=True, verbose_name='사용자 생년월일')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')], max_length=10, null=True, verbose_name='사용자 성별')),
                ('user_height', models.CharField(max_length=3, null=True, verbose_name='사용자 신장')),
                ('user_weight', models.CharField(max_length=3, null=True, verbose_name='사용자 몸무게')),
                ('user_affliction', models.ManyToManyField(blank=True, to='user_info.user_affliction', verbose_name='사용자 고민')),
                ('user_id_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='아이디')),
                ('user_incongruity', models.ManyToManyField(blank=True, to='user_info.user_incongruity', verbose_name='사용자 부적합')),
            ],
            options={
                'verbose_name': '사용자 카드',
                'verbose_name_plural': '사용자 카드',
                'db_table': 'USERCARD_TB',
            },
        ),
    ]
