# Generated by Django 4.1.5 on 2023-10-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': '사용자 정보', 'verbose_name_plural': '사용자 정보'},
        ),
    ]
