# Generated by Django 4.1.5 on 2023-08-14 05:33

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_user_permissions_delete_normaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSMS',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hp', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰번호')),
                ('auth', models.IntegerField(verbose_name='인증번호')),
            ],
            options={
                'db_table': 'AUTH_TB',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(max_length=6, null=True, verbose_name='인증번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='휴대폰번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('2', 'Lv2_사용자'), ('1', 'Lv1_관리자'), ('0', 'Lv0_개발자')], default=2, max_length=18, verbose_name='등급'),
        ),
    ]
