# Generated by Django 4.1.5 on 2023-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_authsms_user_auth_user_hp_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_UserInfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='nuseum_user',
        ),
    ]
